//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_CRUD_Logics.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class AnnouncementComment
    {
        //public int CommentID { get; set; }
        //public Nullable<int> AnnouncementID { get; set; }
        //public Nullable<int> UserID { get; set; }
    
        //public virtual Announcement Announcement { get; set; }
        //public virtual Comment Comment { get; set; }
        //public virtual User User { get; set; }

        [Key]
        public int CommentID { get; set; }

        public int? AnnouncementID { get; set; }

        public int? UserID { get; set; }

        [ForeignKey("AnnouncementID")]
        public virtual Announcement Announcement { get; set; }

        [Required]
        [ForeignKey("CommentID")]
        public virtual Comment Comment { get; set; }

        [Required]
        [ForeignKey("UserID")]
        public virtual User User { get; set; }
    }
}
