//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_CRUD_Logics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Announcement()
        {
            this.AnnouncementComments = new HashSet<AnnouncementComment>();
            this.Bookmarks = new HashSet<Bookmark>();
        }
    
        public int AnnouncementID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string AnnouncementType { get; set; }
        public Nullable<System.DateTime> Date_and_time_of_creation { get; set; }
        public string Campus { get; set; }
        public string Image { get; set; }
        public string Tags { get; set; }
        public string Categories { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnnouncementComment> AnnouncementComments { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
    }
}
