//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_CRUD_Logics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmark
    {
        public int BookmarkID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AnnouncementID { get; set; }
        public Nullable<System.DateTime> Date_and_time_of_creation { get; set; }
    
        public virtual Announcement Announcement { get; set; }
        public virtual User User { get; set; }
    }
}
