//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_CRUD_Logics.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /* public partial class ForumPost
     {
         [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
         public ForumPost()
         {
             this.ForumComments = new HashSet<ForumComment>();
         }

         public int PostID { get; set; }
         public Nullable<int> UserID { get; set; }
         public string Content { get; set; }
         public Nullable<System.DateTime> Date_and_time_of_creation { get; set; }
         public Nullable<int> Number_of_likes { get; set; }
         public Nullable<bool> isApproved { get; set; }
         public string Image { get; set; }
         public string Tags { get; set; }

         [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
         public virtual ICollection<ForumComment> ForumComments { get; set; }
         public virtual User User { get; set; }
     }*/

    public partial class ForumPost
    {
        public ForumPost()
        {
            ForumComments = new HashSet<ForumComment>();
        }
        [Key]
        public int PostID { get; set; }

        public int? UserID { get; set; }
        public string Content { get; set; }
        public DateTime? Date_and_time_of_creation { get; set; }
        public int? Number_of_likes { get; set; }
        public bool? IsApproved { get; set; }
        public string Image { get; set; }
        public string Tags { get; set; }

        
        public virtual ICollection<ForumComment> ForumComments { get; set; }
        [ForeignKey("UserID")]
        public virtual User User { get; set; }
    }
}
