//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_CRUD_Logics.Models
{
    using System;
    using System.Collections.Generic;
    /* 
     public partial class MarketListing
     {
         public int ListingID { get; set; }
         public Nullable<int> UserID { get; set; }
         public string Title { get; set; }
         public string Category { get; set; }
         public string Descriptions { get; set; }
         public string Images { get; set; }
         public Nullable<decimal> Price { get; set; }

         public virtual User User { get; set; }
     }*/
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class MarketListing
    {
        [Key]
        public int ListingID { get; set; }

        public int? UserID { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public string Descriptions { get; set; }
        public string Images { get; set; }
        public decimal? Price { get; set; }

        [ForeignKey("UserID")]
        public virtual User User { get; set; }

    }
}
